"""empty message

Revision ID: 46de514a6494
Revises: 
Create Date: 2019-05-28 16:49:39.102540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46de514a6494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('mac', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('mac')
    )
    op.create_table('log',
    sa.Column('mac', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mac'], ['devices.mac'], ),
    sa.PrimaryKeyConstraint('mac', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('devices')
    # ### end Alembic commands ###
